//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mictlanix.FiscoClic.Client.Internals
{
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
    public partial class FiscoClicException : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("FiscoClicException", "http://srv.soap.factura.sit.mx.com");
        
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://srv.soap.factura.sit.mx.com", ConfigurationName="Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface")]
    public interface cfdiServiceInterface
    {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="timbraCFDIXMLPDFTestAction", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mictlanix.FiscoClic.Client.Internals.FiscoClicException), Action="timbraCFDIXMLPDFTestAction", Name="FiscoClicException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Mictlanix.FiscoClic.Client.Internals.timbraCFDIXMLPDFTestResponse timbraCFDIXMLPDFTest(Mictlanix.FiscoClic.Client.Internals.timbraCFDIXMLPDFTest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="enviaCFDIXMLPDFAction", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mictlanix.FiscoClic.Client.Internals.FiscoClicException), Action="enviaCFDIXMLPDFAction", Name="FiscoClicException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Mictlanix.FiscoClic.Client.Internals.enviaCFDIXMLPDFResponse enviaCFDIXMLPDF(Mictlanix.FiscoClic.Client.Internals.enviaCFDIXMLPDF request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="enviaCFDIXMLPDFTestAction", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mictlanix.FiscoClic.Client.Internals.FiscoClicException), Action="enviaCFDIXMLPDFTestAction", Name="FiscoClicException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Mictlanix.FiscoClic.Client.Internals.enviaCFDIXMLPDFTestResponse enviaCFDIXMLPDFTest(Mictlanix.FiscoClic.Client.Internals.enviaCFDIXMLPDFTest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="validaComprobanteAction", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mictlanix.FiscoClic.Client.Internals.FiscoClicException), Action="validaComprobanteAction", Name="FiscoClicException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Mictlanix.FiscoClic.Client.Internals.validaComprobanteResponse validaComprobante(Mictlanix.FiscoClic.Client.Internals.validaComprobante request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="recuperaCFDIXMLPDFAction", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mictlanix.FiscoClic.Client.Internals.FiscoClicException), Action="recuperaCFDIXMLPDFAction", Name="FiscoClicException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Mictlanix.FiscoClic.Client.Internals.recuperaCFDIXMLPDFResponse recuperaCFDIXMLPDF(Mictlanix.FiscoClic.Client.Internals.recuperaCFDIXMLPDF request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="recuperaCFDIXMLPDFTestAction", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mictlanix.FiscoClic.Client.Internals.FiscoClicException), Action="recuperaCFDIXMLPDFTestAction", Name="FiscoClicException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Mictlanix.FiscoClic.Client.Internals.recuperaCFDIXMLPDFTestResponse recuperaCFDIXMLPDFTest(Mictlanix.FiscoClic.Client.Internals.recuperaCFDIXMLPDFTest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="cancelaCFDIAction", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mictlanix.FiscoClic.Client.Internals.FiscoClicException), Action="cancelaCFDIAction", Name="FiscoClicException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Mictlanix.FiscoClic.Client.Internals.cancelaCFDIResponse cancelaCFDI(Mictlanix.FiscoClic.Client.Internals.cancelaCFDI request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="timbraEnviaCFDIXMLPDFTestAction", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mictlanix.FiscoClic.Client.Internals.FiscoClicException), Action="timbraEnviaCFDIXMLPDFTestAction", Name="FiscoClicException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Mictlanix.FiscoClic.Client.Internals.timbraEnviaCFDIXMLPDFTestResponse timbraEnviaCFDIXMLPDFTest(Mictlanix.FiscoClic.Client.Internals.timbraEnviaCFDIXMLPDFTest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="timbraEnviaCFDIXMLPDFAction", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mictlanix.FiscoClic.Client.Internals.FiscoClicException), Action="timbraEnviaCFDIXMLPDFAction", Name="FiscoClicException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Mictlanix.FiscoClic.Client.Internals.timbraEnviaCFDIXMLPDFResponse timbraEnviaCFDIXMLPDF(Mictlanix.FiscoClic.Client.Internals.timbraEnviaCFDIXMLPDF request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="timbraCFDIXMLPDFAction", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mictlanix.FiscoClic.Client.Internals.FiscoClicException), Action="timbraCFDIXMLPDFAction", Name="FiscoClicException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Mictlanix.FiscoClic.Client.Internals.timbraCFDIXMLPDFResponse timbraCFDIXMLPDF(Mictlanix.FiscoClic.Client.Internals.timbraCFDIXMLPDF request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="timbraCFDIXMLTestAction", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mictlanix.FiscoClic.Client.Internals.FiscoClicException), Action="timbraCFDIXMLTestAction", Name="FiscoClicException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Mictlanix.FiscoClic.Client.Internals.timbraCFDIXMLTestResponse timbraCFDIXMLTest(Mictlanix.FiscoClic.Client.Internals.timbraCFDIXMLTest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="recuperaCFDIXMLAction", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mictlanix.FiscoClic.Client.Internals.FiscoClicException), Action="recuperaCFDIXMLAction", Name="FiscoClicException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Mictlanix.FiscoClic.Client.Internals.recuperaCFDIXMLResponse recuperaCFDIXML(Mictlanix.FiscoClic.Client.Internals.recuperaCFDIXML request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="validaComprobanteTestAction", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mictlanix.FiscoClic.Client.Internals.FiscoClicException), Action="validaComprobanteTestAction", Name="FiscoClicException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Mictlanix.FiscoClic.Client.Internals.validaComprobanteTestResponse validaComprobanteTest(Mictlanix.FiscoClic.Client.Internals.validaComprobanteTest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="enviaTicketsAction", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mictlanix.FiscoClic.Client.Internals.FiscoClicException), Action="enviaTicketsAction", Name="FiscoClicException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Mictlanix.FiscoClic.Client.Internals.enviaTicketsResponse enviaTickets(Mictlanix.FiscoClic.Client.Internals.enviaTickets request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="cancelaCFDITestAction", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mictlanix.FiscoClic.Client.Internals.FiscoClicException), Action="cancelaCFDITestAction", Name="FiscoClicException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Mictlanix.FiscoClic.Client.Internals.cancelaCFDITestResponse cancelaCFDITest(Mictlanix.FiscoClic.Client.Internals.cancelaCFDITest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="recuperaCFDIXMLTestAction", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mictlanix.FiscoClic.Client.Internals.FiscoClicException), Action="recuperaCFDIXMLTestAction", Name="FiscoClicException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Mictlanix.FiscoClic.Client.Internals.recuperaCFDIXMLTestResponse recuperaCFDIXMLTest(Mictlanix.FiscoClic.Client.Internals.recuperaCFDIXMLTest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="timbraCFDIXMLAction", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mictlanix.FiscoClic.Client.Internals.FiscoClicException), Action="timbraCFDIXMLAction", Name="FiscoClicException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Mictlanix.FiscoClic.Client.Internals.timbraCFDIXMLResponse timbraCFDIXML(Mictlanix.FiscoClic.Client.Internals.timbraCFDIXML request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="timbraCFDIXMLPDFTest", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class timbraCFDIXMLPDFTest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        public string cfdi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=1)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=2)]
        public string pass;
        
        public timbraCFDIXMLPDFTest()
        {
        }
        
        public timbraCFDIXMLPDFTest(string cfdi, string user, string pass)
        {
            this.cfdi = cfdi;
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="timbraCFDIXMLPDFTestResponse", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class timbraCFDIXMLPDFTestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] @return;
        
        public timbraCFDIXMLPDFTestResponse()
        {
        }
        
        public timbraCFDIXMLPDFTestResponse(byte[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviaCFDIXMLPDF", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class enviaCFDIXMLPDF
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        public string uuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=1)]
        public string rfcEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=2)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=3)]
        public string pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("correo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] correos;
        
        public enviaCFDIXMLPDF()
        {
        }
        
        public enviaCFDIXMLPDF(string uuid, string rfcEmisor, string user, string pass, string[] correos)
        {
            this.uuid = uuid;
            this.rfcEmisor = rfcEmisor;
            this.user = user;
            this.pass = pass;
            this.correos = correos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviaCFDIXMLPDFResponse", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class enviaCFDIXMLPDFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public enviaCFDIXMLPDFResponse()
        {
        }
        
        public enviaCFDIXMLPDFResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviaCFDIXMLPDFTest", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class enviaCFDIXMLPDFTest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        public string uuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=1)]
        public string rfcEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=2)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=3)]
        public string pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("correo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] correos;
        
        public enviaCFDIXMLPDFTest()
        {
        }
        
        public enviaCFDIXMLPDFTest(string uuid, string rfcEmisor, string user, string pass, string[] correos)
        {
            this.uuid = uuid;
            this.rfcEmisor = rfcEmisor;
            this.user = user;
            this.pass = pass;
            this.correos = correos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviaCFDIXMLPDFTestResponse", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class enviaCFDIXMLPDFTestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public enviaCFDIXMLPDFTestResponse()
        {
        }
        
        public enviaCFDIXMLPDFTestResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validaComprobante", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class validaComprobante
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        public string cfdi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=1)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=2)]
        public string pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=3)]
        public bool analisis;
        
        public validaComprobante()
        {
        }
        
        public validaComprobante(string cfdi, string user, string pass, bool analisis)
        {
            this.cfdi = cfdi;
            this.user = user;
            this.pass = pass;
            this.analisis = analisis;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validaComprobanteResponse", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class validaComprobanteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public validaComprobanteResponse()
        {
        }
        
        public validaComprobanteResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recuperaCFDIXMLPDF", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class recuperaCFDIXMLPDF
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        public string uuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=1)]
        public string rfcEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=2)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=3)]
        public string pass;
        
        public recuperaCFDIXMLPDF()
        {
        }
        
        public recuperaCFDIXMLPDF(string uuid, string rfcEmisor, string user, string pass)
        {
            this.uuid = uuid;
            this.rfcEmisor = rfcEmisor;
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recuperaCFDIXMLPDFResponse", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class recuperaCFDIXMLPDFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] @return;
        
        public recuperaCFDIXMLPDFResponse()
        {
        }
        
        public recuperaCFDIXMLPDFResponse(byte[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recuperaCFDIXMLPDFTest", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class recuperaCFDIXMLPDFTest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        public string uuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=1)]
        public string rfcEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=2)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=3)]
        public string pass;
        
        public recuperaCFDIXMLPDFTest()
        {
        }
        
        public recuperaCFDIXMLPDFTest(string uuid, string rfcEmisor, string user, string pass)
        {
            this.uuid = uuid;
            this.rfcEmisor = rfcEmisor;
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recuperaCFDIXMLPDFTestResponse", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class recuperaCFDIXMLPDFTestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] @return;
        
        public recuperaCFDIXMLPDFTestResponse()
        {
        }
        
        public recuperaCFDIXMLPDFTestResponse(byte[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDI", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class cancelaCFDI
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        public string uuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=1)]
        public string rfcEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=2)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=3)]
        public string pass;
        
        public cancelaCFDI()
        {
        }
        
        public cancelaCFDI(string uuid, string rfcEmisor, string user, string pass)
        {
            this.uuid = uuid;
            this.rfcEmisor = rfcEmisor;
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDIResponse", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class cancelaCFDIResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public cancelaCFDIResponse()
        {
        }
        
        public cancelaCFDIResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="timbraEnviaCFDIXMLPDFTest", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class timbraEnviaCFDIXMLPDFTest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        public string cfdi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=1)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=2)]
        public string pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("correo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] correos;
        
        public timbraEnviaCFDIXMLPDFTest()
        {
        }
        
        public timbraEnviaCFDIXMLPDFTest(string cfdi, string user, string pass, string[] correos)
        {
            this.cfdi = cfdi;
            this.user = user;
            this.pass = pass;
            this.correos = correos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="timbraEnviaCFDIXMLPDFTestResponse", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class timbraEnviaCFDIXMLPDFTestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public timbraEnviaCFDIXMLPDFTestResponse()
        {
        }
        
        public timbraEnviaCFDIXMLPDFTestResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="timbraEnviaCFDIXMLPDF", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class timbraEnviaCFDIXMLPDF
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        public string cfdi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=1)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=2)]
        public string pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("correo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] correos;
        
        public timbraEnviaCFDIXMLPDF()
        {
        }
        
        public timbraEnviaCFDIXMLPDF(string cfdi, string user, string pass, string[] correos)
        {
            this.cfdi = cfdi;
            this.user = user;
            this.pass = pass;
            this.correos = correos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="timbraEnviaCFDIXMLPDFResponse", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class timbraEnviaCFDIXMLPDFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public timbraEnviaCFDIXMLPDFResponse()
        {
        }
        
        public timbraEnviaCFDIXMLPDFResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="timbraCFDIXMLPDF", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class timbraCFDIXMLPDF
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        public string cfdi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=1)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=2)]
        public string pass;
        
        public timbraCFDIXMLPDF()
        {
        }
        
        public timbraCFDIXMLPDF(string cfdi, string user, string pass)
        {
            this.cfdi = cfdi;
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="timbraCFDIXMLPDFResponse", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class timbraCFDIXMLPDFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] @return;
        
        public timbraCFDIXMLPDFResponse()
        {
        }
        
        public timbraCFDIXMLPDFResponse(byte[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="timbraCFDIXMLTest", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class timbraCFDIXMLTest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        public string cfdi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=1)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=2)]
        public string pass;
        
        public timbraCFDIXMLTest()
        {
        }
        
        public timbraCFDIXMLTest(string cfdi, string user, string pass)
        {
            this.cfdi = cfdi;
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="timbraCFDIXMLTestResponse", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class timbraCFDIXMLTestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public timbraCFDIXMLTestResponse()
        {
        }
        
        public timbraCFDIXMLTestResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recuperaCFDIXML", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class recuperaCFDIXML
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        public string uuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=1)]
        public string rfcEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=2)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=3)]
        public string pass;
        
        public recuperaCFDIXML()
        {
        }
        
        public recuperaCFDIXML(string uuid, string rfcEmisor, string user, string pass)
        {
            this.uuid = uuid;
            this.rfcEmisor = rfcEmisor;
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recuperaCFDIXMLResponse", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class recuperaCFDIXMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public recuperaCFDIXMLResponse()
        {
        }
        
        public recuperaCFDIXMLResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validaComprobanteTest", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class validaComprobanteTest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        public string cfdi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=1)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=2)]
        public string pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=3)]
        public bool analisis;
        
        public validaComprobanteTest()
        {
        }
        
        public validaComprobanteTest(string cfdi, string user, string pass, bool analisis)
        {
            this.cfdi = cfdi;
            this.user = user;
            this.pass = pass;
            this.analisis = analisis;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validaComprobanteTestResponse", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class validaComprobanteTestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public validaComprobanteTestResponse()
        {
        }
        
        public validaComprobanteTestResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviaTickets", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class enviaTickets
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        public string comprobantes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=1)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=2)]
        public string pass;
        
        public enviaTickets()
        {
        }
        
        public enviaTickets(string comprobantes, string user, string pass)
        {
            this.comprobantes = comprobantes;
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviaTicketsResponse", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class enviaTicketsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public enviaTicketsResponse()
        {
        }
        
        public enviaTicketsResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDITest", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class cancelaCFDITest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        public string uuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=1)]
        public string rfcEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=2)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=3)]
        public string pass;
        
        public cancelaCFDITest()
        {
        }
        
        public cancelaCFDITest(string uuid, string rfcEmisor, string user, string pass)
        {
            this.uuid = uuid;
            this.rfcEmisor = rfcEmisor;
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDITestResponse", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class cancelaCFDITestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public cancelaCFDITestResponse()
        {
        }
        
        public cancelaCFDITestResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recuperaCFDIXMLTest", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class recuperaCFDIXMLTest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        public string uuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=1)]
        public string rfcEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=2)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=3)]
        public string pass;
        
        public recuperaCFDIXMLTest()
        {
        }
        
        public recuperaCFDIXMLTest(string uuid, string rfcEmisor, string user, string pass)
        {
            this.uuid = uuid;
            this.rfcEmisor = rfcEmisor;
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recuperaCFDIXMLTestResponse", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class recuperaCFDIXMLTestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public recuperaCFDIXMLTestResponse()
        {
        }
        
        public recuperaCFDIXMLTestResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="timbraCFDIXML", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class timbraCFDIXML
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        public string cfdi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=1)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=2)]
        public string pass;
        
        public timbraCFDIXML()
        {
        }
        
        public timbraCFDIXML(string cfdi, string user, string pass)
        {
            this.cfdi = cfdi;
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="timbraCFDIXMLResponse", WrapperNamespace="http://srv.soap.factura.sit.mx.com", IsWrapped=true)]
    public partial class timbraCFDIXMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://srv.soap.factura.sit.mx.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public timbraCFDIXMLResponse()
        {
        }
        
        public timbraCFDIXMLResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface cfdiServiceInterfaceChannel : Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class cfdiServiceInterfaceClient : System.ServiceModel.ClientBase<Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface>, Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface
    {
        
        public cfdiServiceInterfaceClient()
        {
        }
        
        public cfdiServiceInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public cfdiServiceInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public cfdiServiceInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public cfdiServiceInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mictlanix.FiscoClic.Client.Internals.timbraCFDIXMLPDFTestResponse Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface.timbraCFDIXMLPDFTest(Mictlanix.FiscoClic.Client.Internals.timbraCFDIXMLPDFTest request)
        {
            return base.Channel.timbraCFDIXMLPDFTest(request);
        }
        
        public byte[] timbraCFDIXMLPDFTest(string cfdi, string user, string pass)
        {
            Mictlanix.FiscoClic.Client.Internals.timbraCFDIXMLPDFTest inValue = new Mictlanix.FiscoClic.Client.Internals.timbraCFDIXMLPDFTest();
            inValue.cfdi = cfdi;
            inValue.user = user;
            inValue.pass = pass;
            Mictlanix.FiscoClic.Client.Internals.timbraCFDIXMLPDFTestResponse retVal = ((Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface)(this)).timbraCFDIXMLPDFTest(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mictlanix.FiscoClic.Client.Internals.enviaCFDIXMLPDFResponse Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface.enviaCFDIXMLPDF(Mictlanix.FiscoClic.Client.Internals.enviaCFDIXMLPDF request)
        {
            return base.Channel.enviaCFDIXMLPDF(request);
        }
        
        public bool enviaCFDIXMLPDF(string uuid, string rfcEmisor, string user, string pass, string[] correos)
        {
            Mictlanix.FiscoClic.Client.Internals.enviaCFDIXMLPDF inValue = new Mictlanix.FiscoClic.Client.Internals.enviaCFDIXMLPDF();
            inValue.uuid = uuid;
            inValue.rfcEmisor = rfcEmisor;
            inValue.user = user;
            inValue.pass = pass;
            inValue.correos = correos;
            Mictlanix.FiscoClic.Client.Internals.enviaCFDIXMLPDFResponse retVal = ((Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface)(this)).enviaCFDIXMLPDF(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mictlanix.FiscoClic.Client.Internals.enviaCFDIXMLPDFTestResponse Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface.enviaCFDIXMLPDFTest(Mictlanix.FiscoClic.Client.Internals.enviaCFDIXMLPDFTest request)
        {
            return base.Channel.enviaCFDIXMLPDFTest(request);
        }
        
        public bool enviaCFDIXMLPDFTest(string uuid, string rfcEmisor, string user, string pass, string[] correos)
        {
            Mictlanix.FiscoClic.Client.Internals.enviaCFDIXMLPDFTest inValue = new Mictlanix.FiscoClic.Client.Internals.enviaCFDIXMLPDFTest();
            inValue.uuid = uuid;
            inValue.rfcEmisor = rfcEmisor;
            inValue.user = user;
            inValue.pass = pass;
            inValue.correos = correos;
            Mictlanix.FiscoClic.Client.Internals.enviaCFDIXMLPDFTestResponse retVal = ((Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface)(this)).enviaCFDIXMLPDFTest(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mictlanix.FiscoClic.Client.Internals.validaComprobanteResponse Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface.validaComprobante(Mictlanix.FiscoClic.Client.Internals.validaComprobante request)
        {
            return base.Channel.validaComprobante(request);
        }
        
        public string validaComprobante(string cfdi, string user, string pass, bool analisis)
        {
            Mictlanix.FiscoClic.Client.Internals.validaComprobante inValue = new Mictlanix.FiscoClic.Client.Internals.validaComprobante();
            inValue.cfdi = cfdi;
            inValue.user = user;
            inValue.pass = pass;
            inValue.analisis = analisis;
            Mictlanix.FiscoClic.Client.Internals.validaComprobanteResponse retVal = ((Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface)(this)).validaComprobante(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mictlanix.FiscoClic.Client.Internals.recuperaCFDIXMLPDFResponse Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface.recuperaCFDIXMLPDF(Mictlanix.FiscoClic.Client.Internals.recuperaCFDIXMLPDF request)
        {
            return base.Channel.recuperaCFDIXMLPDF(request);
        }
        
        public byte[] recuperaCFDIXMLPDF(string uuid, string rfcEmisor, string user, string pass)
        {
            Mictlanix.FiscoClic.Client.Internals.recuperaCFDIXMLPDF inValue = new Mictlanix.FiscoClic.Client.Internals.recuperaCFDIXMLPDF();
            inValue.uuid = uuid;
            inValue.rfcEmisor = rfcEmisor;
            inValue.user = user;
            inValue.pass = pass;
            Mictlanix.FiscoClic.Client.Internals.recuperaCFDIXMLPDFResponse retVal = ((Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface)(this)).recuperaCFDIXMLPDF(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mictlanix.FiscoClic.Client.Internals.recuperaCFDIXMLPDFTestResponse Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface.recuperaCFDIXMLPDFTest(Mictlanix.FiscoClic.Client.Internals.recuperaCFDIXMLPDFTest request)
        {
            return base.Channel.recuperaCFDIXMLPDFTest(request);
        }
        
        public byte[] recuperaCFDIXMLPDFTest(string uuid, string rfcEmisor, string user, string pass)
        {
            Mictlanix.FiscoClic.Client.Internals.recuperaCFDIXMLPDFTest inValue = new Mictlanix.FiscoClic.Client.Internals.recuperaCFDIXMLPDFTest();
            inValue.uuid = uuid;
            inValue.rfcEmisor = rfcEmisor;
            inValue.user = user;
            inValue.pass = pass;
            Mictlanix.FiscoClic.Client.Internals.recuperaCFDIXMLPDFTestResponse retVal = ((Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface)(this)).recuperaCFDIXMLPDFTest(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mictlanix.FiscoClic.Client.Internals.cancelaCFDIResponse Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface.cancelaCFDI(Mictlanix.FiscoClic.Client.Internals.cancelaCFDI request)
        {
            return base.Channel.cancelaCFDI(request);
        }
        
        public bool cancelaCFDI(string uuid, string rfcEmisor, string user, string pass)
        {
            Mictlanix.FiscoClic.Client.Internals.cancelaCFDI inValue = new Mictlanix.FiscoClic.Client.Internals.cancelaCFDI();
            inValue.uuid = uuid;
            inValue.rfcEmisor = rfcEmisor;
            inValue.user = user;
            inValue.pass = pass;
            Mictlanix.FiscoClic.Client.Internals.cancelaCFDIResponse retVal = ((Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface)(this)).cancelaCFDI(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mictlanix.FiscoClic.Client.Internals.timbraEnviaCFDIXMLPDFTestResponse Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface.timbraEnviaCFDIXMLPDFTest(Mictlanix.FiscoClic.Client.Internals.timbraEnviaCFDIXMLPDFTest request)
        {
            return base.Channel.timbraEnviaCFDIXMLPDFTest(request);
        }
        
        public bool timbraEnviaCFDIXMLPDFTest(string cfdi, string user, string pass, string[] correos)
        {
            Mictlanix.FiscoClic.Client.Internals.timbraEnviaCFDIXMLPDFTest inValue = new Mictlanix.FiscoClic.Client.Internals.timbraEnviaCFDIXMLPDFTest();
            inValue.cfdi = cfdi;
            inValue.user = user;
            inValue.pass = pass;
            inValue.correos = correos;
            Mictlanix.FiscoClic.Client.Internals.timbraEnviaCFDIXMLPDFTestResponse retVal = ((Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface)(this)).timbraEnviaCFDIXMLPDFTest(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mictlanix.FiscoClic.Client.Internals.timbraEnviaCFDIXMLPDFResponse Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface.timbraEnviaCFDIXMLPDF(Mictlanix.FiscoClic.Client.Internals.timbraEnviaCFDIXMLPDF request)
        {
            return base.Channel.timbraEnviaCFDIXMLPDF(request);
        }
        
        public bool timbraEnviaCFDIXMLPDF(string cfdi, string user, string pass, string[] correos)
        {
            Mictlanix.FiscoClic.Client.Internals.timbraEnviaCFDIXMLPDF inValue = new Mictlanix.FiscoClic.Client.Internals.timbraEnviaCFDIXMLPDF();
            inValue.cfdi = cfdi;
            inValue.user = user;
            inValue.pass = pass;
            inValue.correos = correos;
            Mictlanix.FiscoClic.Client.Internals.timbraEnviaCFDIXMLPDFResponse retVal = ((Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface)(this)).timbraEnviaCFDIXMLPDF(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mictlanix.FiscoClic.Client.Internals.timbraCFDIXMLPDFResponse Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface.timbraCFDIXMLPDF(Mictlanix.FiscoClic.Client.Internals.timbraCFDIXMLPDF request)
        {
            return base.Channel.timbraCFDIXMLPDF(request);
        }
        
        public byte[] timbraCFDIXMLPDF(string cfdi, string user, string pass)
        {
            Mictlanix.FiscoClic.Client.Internals.timbraCFDIXMLPDF inValue = new Mictlanix.FiscoClic.Client.Internals.timbraCFDIXMLPDF();
            inValue.cfdi = cfdi;
            inValue.user = user;
            inValue.pass = pass;
            Mictlanix.FiscoClic.Client.Internals.timbraCFDIXMLPDFResponse retVal = ((Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface)(this)).timbraCFDIXMLPDF(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mictlanix.FiscoClic.Client.Internals.timbraCFDIXMLTestResponse Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface.timbraCFDIXMLTest(Mictlanix.FiscoClic.Client.Internals.timbraCFDIXMLTest request)
        {
            return base.Channel.timbraCFDIXMLTest(request);
        }
        
        public string timbraCFDIXMLTest(string cfdi, string user, string pass)
        {
            Mictlanix.FiscoClic.Client.Internals.timbraCFDIXMLTest inValue = new Mictlanix.FiscoClic.Client.Internals.timbraCFDIXMLTest();
            inValue.cfdi = cfdi;
            inValue.user = user;
            inValue.pass = pass;
            Mictlanix.FiscoClic.Client.Internals.timbraCFDIXMLTestResponse retVal = ((Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface)(this)).timbraCFDIXMLTest(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mictlanix.FiscoClic.Client.Internals.recuperaCFDIXMLResponse Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface.recuperaCFDIXML(Mictlanix.FiscoClic.Client.Internals.recuperaCFDIXML request)
        {
            return base.Channel.recuperaCFDIXML(request);
        }
        
        public string recuperaCFDIXML(string uuid, string rfcEmisor, string user, string pass)
        {
            Mictlanix.FiscoClic.Client.Internals.recuperaCFDIXML inValue = new Mictlanix.FiscoClic.Client.Internals.recuperaCFDIXML();
            inValue.uuid = uuid;
            inValue.rfcEmisor = rfcEmisor;
            inValue.user = user;
            inValue.pass = pass;
            Mictlanix.FiscoClic.Client.Internals.recuperaCFDIXMLResponse retVal = ((Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface)(this)).recuperaCFDIXML(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mictlanix.FiscoClic.Client.Internals.validaComprobanteTestResponse Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface.validaComprobanteTest(Mictlanix.FiscoClic.Client.Internals.validaComprobanteTest request)
        {
            return base.Channel.validaComprobanteTest(request);
        }
        
        public string validaComprobanteTest(string cfdi, string user, string pass, bool analisis)
        {
            Mictlanix.FiscoClic.Client.Internals.validaComprobanteTest inValue = new Mictlanix.FiscoClic.Client.Internals.validaComprobanteTest();
            inValue.cfdi = cfdi;
            inValue.user = user;
            inValue.pass = pass;
            inValue.analisis = analisis;
            Mictlanix.FiscoClic.Client.Internals.validaComprobanteTestResponse retVal = ((Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface)(this)).validaComprobanteTest(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mictlanix.FiscoClic.Client.Internals.enviaTicketsResponse Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface.enviaTickets(Mictlanix.FiscoClic.Client.Internals.enviaTickets request)
        {
            return base.Channel.enviaTickets(request);
        }
        
        public string enviaTickets(string comprobantes, string user, string pass)
        {
            Mictlanix.FiscoClic.Client.Internals.enviaTickets inValue = new Mictlanix.FiscoClic.Client.Internals.enviaTickets();
            inValue.comprobantes = comprobantes;
            inValue.user = user;
            inValue.pass = pass;
            Mictlanix.FiscoClic.Client.Internals.enviaTicketsResponse retVal = ((Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface)(this)).enviaTickets(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mictlanix.FiscoClic.Client.Internals.cancelaCFDITestResponse Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface.cancelaCFDITest(Mictlanix.FiscoClic.Client.Internals.cancelaCFDITest request)
        {
            return base.Channel.cancelaCFDITest(request);
        }
        
        public bool cancelaCFDITest(string uuid, string rfcEmisor, string user, string pass)
        {
            Mictlanix.FiscoClic.Client.Internals.cancelaCFDITest inValue = new Mictlanix.FiscoClic.Client.Internals.cancelaCFDITest();
            inValue.uuid = uuid;
            inValue.rfcEmisor = rfcEmisor;
            inValue.user = user;
            inValue.pass = pass;
            Mictlanix.FiscoClic.Client.Internals.cancelaCFDITestResponse retVal = ((Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface)(this)).cancelaCFDITest(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mictlanix.FiscoClic.Client.Internals.recuperaCFDIXMLTestResponse Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface.recuperaCFDIXMLTest(Mictlanix.FiscoClic.Client.Internals.recuperaCFDIXMLTest request)
        {
            return base.Channel.recuperaCFDIXMLTest(request);
        }
        
        public string recuperaCFDIXMLTest(string uuid, string rfcEmisor, string user, string pass)
        {
            Mictlanix.FiscoClic.Client.Internals.recuperaCFDIXMLTest inValue = new Mictlanix.FiscoClic.Client.Internals.recuperaCFDIXMLTest();
            inValue.uuid = uuid;
            inValue.rfcEmisor = rfcEmisor;
            inValue.user = user;
            inValue.pass = pass;
            Mictlanix.FiscoClic.Client.Internals.recuperaCFDIXMLTestResponse retVal = ((Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface)(this)).recuperaCFDIXMLTest(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mictlanix.FiscoClic.Client.Internals.timbraCFDIXMLResponse Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface.timbraCFDIXML(Mictlanix.FiscoClic.Client.Internals.timbraCFDIXML request)
        {
            return base.Channel.timbraCFDIXML(request);
        }
        
        public string timbraCFDIXML(string cfdi, string user, string pass)
        {
            Mictlanix.FiscoClic.Client.Internals.timbraCFDIXML inValue = new Mictlanix.FiscoClic.Client.Internals.timbraCFDIXML();
            inValue.cfdi = cfdi;
            inValue.user = user;
            inValue.pass = pass;
            Mictlanix.FiscoClic.Client.Internals.timbraCFDIXMLResponse retVal = ((Mictlanix.FiscoClic.Client.Internals.cfdiServiceInterface)(this)).timbraCFDIXML(inValue);
            return retVal.@return;
        }
    }
}
